#include "labdaq_control.h"
#include <string.h>
#include <stdio.h>
#include "stm32f4xx_hal.h"
labdaq_control_t g_labdaq_control;
void LABDAQ_Log(uint8_t level,const char *text){ labdaq_log_entry_t *e=&g_labdaq_control.logs[g_labdaq_control.log_head]; e->timestamp_s=LABDAQ_Time_NowUnix();e->level=level;snprintf(e->text,sizeof(e->text),"%s",text?text:"");g_labdaq_control.log_head=(g_labdaq_control.log_head+1U)%LABDAQ_LOG_CAPACITY;if(g_labdaq_control.log_count<LABDAQ_LOG_CAPACITY)g_labdaq_control.log_count++; }
void LABDAQ_Control_Init(void){ memset(&g_labdaq_control,0,sizeof(g_labdaq_control)); g_labdaq_control.tick_at_set=HAL_GetTick();g_labdaq_control.experiment_type=LABDAQ_TEST_CYCLIC_TRIAXIAL;g_labdaq_control.frequency_hz=1.0f;g_labdaq_control.target_cycles=10000; for(int i=0;i<LABDAQ_NUM_CHANNELS;i++){snprintf(g_labdaq_control.channel[i].name,LABDAQ_NAME_LEN,"CH%02d",i+1);snprintf(g_labdaq_control.channel[i].unit,12,"mV");g_labdaq_control.channel[i].gain=1.0f;g_labdaq_control.channel[i].enabled=true;} for(int m=0;m<2;m++){g_labdaq_control.motor_pid[m].output_min=0;g_labdaq_control.motor_pid[m].output_max=10;g_labdaq_control.motor_cal[m].command_min_v=0;g_labdaq_control.motor_cal[m].command_max_v=10;} LABDAQ_Log(1,"Control subsystem initialized");}
void LABDAQ_Time_SetUnix(uint32_t epoch){g_labdaq_control.epoch_at_set=epoch;g_labdaq_control.tick_at_set=HAL_GetTick();LABDAQ_Log(1,"Clock updated");}
uint32_t LABDAQ_Time_NowUnix(void){return g_labdaq_control.epoch_at_set+(HAL_GetTick()-g_labdaq_control.tick_at_set)/1000U;}
void LABDAQ_Channel_Set(uint8_t ch,const char *name,const char *unit,float gain,float offset){if(ch>=LABDAQ_NUM_CHANNELS)return;if(name)snprintf(g_labdaq_control.channel[ch].name,LABDAQ_NAME_LEN,"%s",name);if(unit)snprintf(g_labdaq_control.channel[ch].unit,12,"%s",unit);g_labdaq_control.channel[ch].gain=gain;g_labdaq_control.channel[ch].offset=offset;LABDAQ_Log(1,"Channel calibration changed");}
float LABDAQ_Channel_Engineering(uint8_t ch,float input){if(ch>=LABDAQ_NUM_CHANNELS)return input;return input*g_labdaq_control.channel[ch].gain+g_labdaq_control.channel[ch].offset;}
void LABDAQ_PID_Set(uint8_t m,float kp,float ki,float kd,float sp){if(m>=2)return;labdaq_pid_t*p=&g_labdaq_control.motor_pid[m];p->kp=kp;p->ki=ki;p->kd=kd;p->setpoint=sp;p->integral=0;p->prev_error=0;p->enabled=true;LABDAQ_Log(1,"PID parameters updated");}
float LABDAQ_PID_Update(uint8_t m,float fb,float dt){if(m>=2||dt<=0)return 0;labdaq_pid_t*p=&g_labdaq_control.motor_pid[m];float e=p->setpoint-fb;p->integral+=e*dt;float out=p->kp*e+p->ki*p->integral+p->kd*(e-p->prev_error)/dt;p->prev_error=e;if(out<p->output_min)out=p->output_min;if(out>p->output_max)out=p->output_max;return out;}
void LABDAQ_Motor_SetCalibration(uint8_t m,float cmin,float cmax,float fmin,float fmax){if(m>=2||cmax<=cmin||fmax==fmin)return;labdaq_motor_cal_t*c=&g_labdaq_control.motor_cal[m];c->command_min_v=cmin;c->command_max_v=cmax;c->feedback_min=fmin;c->feedback_max=fmax;c->gain=(cmax-cmin)/(fmax-fmin);c->offset=cmin-c->gain*fmin;c->calibrated=true;LABDAQ_Log(1,"EP motor calibration updated");}
void LABDAQ_Control_Task(labdaq_system_t *sys){(void)sys;/* Closed-loop outputs are intentionally gated until physical DAC/PWM-to-10V mapping is commissioned. */ }
